name: deploy to aws s3
# main 브랜치에 push될 때 현재 스크립트 실행 trigger 발동
on:
  push:
    branches:
      -main
jobs:
# 워크 플로우는 하나 이상의 작업(job)으로 구성. 여기서는 하나의 작업만을 정의
  build-and-deploy:
    runs-on: ubuntu-latest
    # 각 작업은 여러 step(단계)로 구성.
    steps:
    # actions는 github에서 제공되는 공식 워크플로우
    # checkout은 현재 repo의 main 브랜치 소스코드를 copy
      - name: source code checkout # 이름 지정 가능
        uses: actions/checkout@v2
      
      - name: setup node.js # 노드 설치
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        
      - name: npm install
        working-directory: .
        # run은 직접 사용하고자 하는 명령어
        run: npm install

      - name: npm build
        working-directory: .
        run: npm run build



